### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastTransforms.jl#78]
```julia
(v1.2) pkg> generate NewFastTransforms
Generating project NewFastTransforms:
    NewFastTransforms/Project.toml
    NewFastTransforms/src/NewFastTransforms.jl

(v1.2) pkg> activate NewFastTransforms
Activating environment at `~/Documents/Coding/NewFastTransforms/Project.toml`

(NewFastTransforms) pkg> dev /Users/solver/Projects/FastTransforms.jl/
 Resolving package versions...
  Updating `~/Documents/Coding/NewFastTransforms/Project.toml`
  [057dd010] + FastTransforms v0.7.0 [`~/Projects/FastTransforms.jl`]
  Updating `~/Documents/Coding/NewFastTransforms/Manifest.toml`
  [621f4979] + AbstractFFTs v0.4.1
  [9e28174c] + BinDeps v0.8.10
  [b99e7846] + BinaryProvider v0.5.6
  [34da2185] + Compat v2.1.0
  [8f4d0f93] + Conda v1.3.0
  [717857b8] + DSP v0.6.0
  [9a962f9c] + DataAPI v1.0.1
  [864edb3b] + DataStructures v0.17.0
  [7a1cc6ca] + FFTW v1.0.0
  [442a2c76] + FastGaussQuadrature v0.4.0
  [057dd010] + FastTransforms v0.7.0 [`~/Projects/FastTransforms.jl`]
  [682c06a0] + JSON v0.21.0
  [e1d29d7a] + Missings v0.4.2
  [bac558e1] + OrderedCollections v1.1.0
  [69de0a69] + Parsers v0.3.7
  [f27b6e38] + Polynomials v0.5.2
  [189a3867] + Reexport v0.2.0
  [a2af1166] + SortingAlgorithms v0.3.1
  [276daf66] + SpecialFunctions v0.8.0
  [2913bbd2] + StatsBase v0.32.0
  [c751599d] + ToeplitzMatrices v0.6.0
  [30578b45] + URIParser v0.4.0
  [81def892] + VersionParsing v1.1.3
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 

(NewFastTransforms) pkg> build FastTransforms
  Building Conda ───────────→ `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building FFTW ────────────→ `~/.julia/packages/FFTW/xi4tZ/deps/build.log`
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/ne2iw/deps/build.log`
  Building FastTransforms ──→ `~/Projects/FastTransforms.jl/deps/build.log`
 Resolving package versions...

julia> using FastTransforms
[ Info: Precompiling FastTransforms [057dd010-8810-581a-b7be-e3fc3b93f78c]
ERROR: LoadError: LoadError: FastTransforms is not properly installed. Please run Pkg.build("FastTransforms") and restart Julia.
Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] top-level scope at /Users/solver/Projects/FastTransforms.jl/src/libfasttransforms.jl:19
 [3] include at ./boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1094
 [5] include at ./Base.jl:31 [inlined]
 [6] include(::String) at /Users/solver/Projects/FastTransforms.jl/src/FastTransforms.jl:1
 [7] top-level scope at /Users/solver/Projects/FastTransforms.jl/src/FastTransforms.jl:39
 [8] include at ./boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1094
 [10] include(::Module, ::String) at ./Base.jl:31
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:330 [inlined]
 [13] eval(::Expr) at ./client.jl:432
 [14] top-level scope at ./none:3
in expression starting at /Users/solver/Projects/FastTransforms.jl/src/libfasttransforms.jl:18
in expression starting at /Users/solver/Projects/FastTransforms.jl/src/FastTransforms.jl:39
ERROR: Failed to precompile FastTransforms [057dd010-8810-581a-b7be-e3fc3b93f78c] to /Users/solver/.julia/compiled/v1.2/FastTransforms/5Lm8s.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1253
 [3] _require(::Base.PkgId) at ./loading.jl:1013
 [4] require(::Base.PkgId) at ./loading.jl:911
 [5] require(::Module, ::Symbol) at ./loading.jl:906
```

**Comment by dlfivefifty** [comment]
I tried following the instructions in libfasttransforms.jl but it didn't work:
```
[solver-mbook:~/Projects/FastTransforms.jl/deps/FastTransforms] solver% make CC=gcc-8
make assembly
gcc-8 -S -std=gnu99 -Ofast -march=native -mtune=native -mno-vzeroupper -I./src -I/usr/local/opt/openblas/include test/test_assembly.c -o test_assembly.s
make lib
gcc-8 -std=gnu99 -Ofast -march=native -mtune=native -mno-vzeroupper -I./src -I/usr/local/opt/openblas/include -shared -lm -fPIC src/transforms.c src/rotations.c src/permute.c src/tdc.c src/drivers.c src/fftw.c -L/usr/local/opt/openblas/lib -lm -lquadmath -fopenmp -lblas -lfftw3 -lfftw3_threads -lmpfr -lgmp -o libfasttransforms.dylib
In file included from src/transforms.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/rotations.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/tdc.c:1:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/drivers.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/fftw.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [lib] Error 1
make: *** [all] Error 2
```

**Comment by MikaelSlevinsky** [comment]
The second issue is my mistake. In Mojave, Apple took out /usr/local from the default search path, so include and link paths to fftw and mpfr and gmp (and openblas) have to be added. I have a commit at my workstation for this, just didn’t push.

But more importantly, it would be better to know why downloading the binaries didn’t work for you. What does the build.log say? One receives the warning because the library is not dlopen-able. This happens when one of its dependencies is not where it thinks it is. What does

otool -L libfasttransforms.dylib

say? Have you brew installed mpfr?

Cheers,

Mikael

On Sep 10, 2019, at 8:38 AM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried following the instructions in libfasttransforms.jl but it didn't work:

[solver-mbook:~/Projects/FastTransforms.jl/deps/FastTransforms] solver% make CC=gcc-8
make assembly
gcc-8 -S -std=gnu99 -Ofast -march=native -mtune=native -mno-vzeroupper -I./src -I/usr/local/opt/openblas/include test/test_assembly.c -o test_assembly.s
make lib
gcc-8 -std=gnu99 -Ofast -march=native -mtune=native -mno-vzeroupper -I./src -I/usr/local/opt/openblas/include -shared -lm -fPIC src/transforms.c src/rotations.c src/permute.c src/tdc.c src/drivers.c src/fftw.c -L/usr/local/opt/openblas/lib -lm -lquadmath -fopenmp -lblas -lfftw3 -lfftw3_threads -lmpfr -lgmp -o libfasttransforms.dylib
In file included from src/transforms.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/rotations.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/tdc.c:1:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/drivers.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
In file included from src/fftw.c:3:
src/fasttransforms.h:9:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [lib] Error 1
make: *** [all] Error 2

**Comment by dlfivefifty** [comment]
The binaries work fine if I `]add FastTransforms#master`, which I'll do now

**Comment by MikaelSlevinsky** [comment]
The make issues should now be fixed with v0.2.7.

**Comment by MikaelSlevinsky** [comment]
When you're developing in a new environment, is `const libfasttransforms = joinpath(dirname(@__DIR__), "deps", "libfasttransforms.dylib")` the correct path?

**Comment by dlfivefifty** [comment]
Yes, and in fact it now works fine when I dev having "tried and failed" to build from source...

**Comment by MikaelSlevinsky** [comment]
Building from source should work now too

**Comment by ReneM92** [comment]
Hi, I am still having this issue also after `]add FastTransforms#master.`  
The build log  after `Pkg.build("FastTransforms")` contains 

> FastTransforms installed by downloading binaries.

However, this gives me the message false.

**Comment by ReneM92** [comment]
After precompiling my packages the package seems to be build correctly now.

**Comment by dlfivefifty** [comment]
I had to use an old computer and the build appears to work (says it downloaded the library), however, the package won't load. I tried manually using the libfasttransforms path without success:
```julia
julia> const libfasttransforms = "/Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib"
"/Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib"

julia> n = 5
5

julia> ccall((:ft_fftw_plan_with_nthreads, libfasttransforms), Cvoid, (Cint, ), n)
ERROR: error compiling top-level scope: could not load library "/Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib"
dlopen(/Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib, 1): Library not loaded: /usr/local/opt/gcc@8/lib/gcc/8/libquadmath.0.dylib
  Referenced from: /Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib
  Reason: image not found
caused by [exception 1]
could not load library "/Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib"
dlopen(/Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib, 1): Library not loaded: /usr/local/opt/gcc@8/lib/gcc/8/libquadmath.0.dylib
  Referenced from: /Users/solver/.julia/packages/FastTransforms/M6SJL/deps/libfasttransforms.dylib
  Reason: image not found
```

**Comment by MikaelSlevinsky** [comment]
I think the error is saying that it can't find all dependencies where it thinks they're supposed to be. Maybe try `brew install gcc@8 fftw mpfr`? Might need a `brew update` too

**Comment by dlfivefifty** [comment]
Ok but you can’t assume a user has these installed.

**Comment by dlfivefifty** [comment]
This is annoying: I decided to tag a FastTransforms.jl v0.6.1 to update some packages, only to realise that Julia v1.3's new Threading model is not compatible with FastTransforms.jl! So basically we need to use FastTransforms.jl v0.7 for Julia v1.3+ anyways...

**Comment by MikaelSlevinsky** [comment]
It should be straightforward to remove the stepthreading code to maintain 0.6; I think it's just one file and the macro @stepthreads.

We are just two pull requests from autogeneration of a `FastTransforms_jll` package of precompiled binaries for all Intel processors. The first (https://github.com/JuliaPackaging/Yggdrasil/pull/207) would fix `CompilerSupportLibraries_jll`, and the second (https://github.com/JuliaPackaging/Yggdrasil/pull/206) is the `FastTransforms_jll` builder. The artifacts system on Julia v1.3 is one of the most awesome developments in the language.
